import AppKit
import UniformTypeIdentifiers

@objc(ShareController) final class ShareController: NSViewController {
    let field = NSTextField(); let status = NSTextField(labelWithString: "将内容保存到收集箱，下次打开Zilo时导入。")
    override func loadView() { view = NSView(frame: NSRect(x: 0,y: 0,width: 430,height: 160)); field.frame = NSRect(x: 20,y: 90,width: 390,height: 24); status.frame = NSRect(x: 20,y: 60,width: 390,height: 20); let add = NSButton(title: "保存任务",target: self,action: #selector(save)); add.frame = NSRect(x: 310,y: 15,width: 100,height: 30); let cancel = NSButton(title: "取消",target: self,action: #selector(cancel)); cancel.frame = NSRect(x: 220,y: 15,width: 80,height: 30); view.addSubview(field); view.addSubview(status); view.addSubview(add); view.addSubview(cancel) }
    override func viewDidLoad() { super.viewDidLoad(); for item in extensionContext?.inputItems as? [NSExtensionItem] ?? [] { if let text = item.attributedContentText { field.stringValue = text.string }; for provider in item.attachments ?? [] { let type = provider.hasItemConformingToTypeIdentifier(UTType.url.identifier) ? UTType.url.identifier : UTType.plainText.identifier; if provider.hasItemConformingToTypeIdentifier(type) { provider.loadItem(forTypeIdentifier: type,options: nil) { [weak self] value,_ in DispatchQueue.main.async { if let url = value as? URL { self?.field.stringValue = url.absoluteString } else if let text = value as? String { self?.field.stringValue = text } } } } } } }
    @objc func save() { guard !field.stringValue.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { status.stringValue = "请输入任务内容"; return }; guard let root = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: Bundle.main.object(forInfoDictionaryKey: "OwnListAppGroup") as? String ?? "VFDQL6Z55P.com.gaoluchuan.ownlist") else { status.stringValue = "共享容器不可用，请检查应用签名"; return }; let queue = root.appendingPathComponent("SharedInbox"); do { try FileManager.default.createDirectory(at: queue,withIntermediateDirectories: true); try field.stringValue.write(to: queue.appendingPathComponent(UUID().uuidString + ".txt"),atomically: true,encoding: .utf8); extensionContext?.completeRequest(returningItems: nil) } catch { status.stringValue = error.localizedDescription } }
    @objc func cancel() { extensionContext?.cancelRequest(withError: NSError(domain: NSCocoaErrorDomain,code: NSUserCancelledError)) }
}
