import SwiftUI

struct CalendarView: View {
    @EnvironmentObject var store: Store; @EnvironmentObject var service: CalendarService
    var compact = false
    @State private var date = Date(); @State private var mode = "月"; @State private var showHabits = true; @State private var showFocus = true; @State private var zoom = 50.0; @State private var secondaryZone = "Asia/Hong_Kong"; @State private var editing: UUID?
    var body: some View { VStack(alignment: .leading,spacing: 16) {
        HStack { Text("日历").font(.largeTitle.bold()); Spacer(); Button("今天") { date = Date() }; Button { advance(-1) } label: { Image(systemName: "chevron.left") }; Text(date,format: .dateTime.year().month()).font(.headline); Button { advance(1) } label: { Image(systemName: "chevron.right") } }
        HStack { Picker("视图",selection: $mode) { ForEach(["年","月","周","日","日程","课表"],id: \.self) { Text($0) } }.pickerStyle(.segmented); Menu { Toggle("习惯",isOn: $showHabits); Toggle("专注记录",isOn: $showFocus); Picker("辅助时区",selection: $secondaryZone) { ForEach(["Asia/Hong_Kong","Asia/Tokyo","Europe/London","America/New_York","America/Los_Angeles"],id: \.self) { Text($0) } }; Slider(value: $zoom,in: 30...100) { Text("时间轴缩放") } } label: { Image(systemName: "slider.horizontal.3") } }
        if mode == "年" { ScrollView { LazyVGrid(columns: Array(repeating: GridItem(.flexible()),count: compact ? 2 : 3),spacing: 18) { ForEach(1...12,id: \.self) { month in let d = Calendar.current.date(from: DateComponents(year: Calendar.current.component(.year,from: date),month: month,day: 1))!; VStack { Button("\(month) 月") { date = d; mode = "月" }.font(.headline); monthGrid(d,mini: true) }.padding(8).background(ListTheme.input,in: RoundedRectangle(cornerRadius: 12)) } } } }
        else if mode == "月" { ScrollView { monthGrid(date,mini: false) } }
        else if ["周","日","课表"].contains(mode) { timeGrid }
        else { ScrollView { LazyVStack(alignment: .leading,spacing: 14) { ForEach(0..<30,id: \.self) { offset in let day = Calendar.current.date(byAdding: .day,value: offset,to: Calendar.current.startOfDay(for: date))!; if !dayTasks(day).isEmpty || !dayEvents(day).isEmpty { Text(day,format: .dateTime.weekday().month().day()).font(.headline); dayContent(day,limit: 100) } } } } }
        if !service.message.isEmpty { Text(service.message).font(.caption).foregroundStyle(.secondary) }
    }.padding(compact ? 12 : 24).task { service.refresh(); for sub in store.subscriptions.filter({ !$0.deleted }) { do { try await service.subscribe(sub.url,name: sub.name) } catch { service.message = error.localizedDescription } } }
        .sheet(item: Binding(get: { editing.flatMap { id in store.tasks.first { $0.id == id } } },set: { editing = $0?.id })) { task in TaskDetailView().environmentObject(store).environmentObject(service).frame(width: 450,height: 700).onAppear { store.selectedTask = task.id } }
    }
    func advance(_ amount: Int) { date = Calendar.current.date(byAdding: mode == "年" ? .year : mode == "月" ? .month : mode == "周" || mode == "课表" ? .weekOfYear : .day,value: amount,to: date)! }
    func dayTasks(_ day: Date) -> [TaskItem] { store.tasks.filter { !$0.deleted && !$0.isTemplate && $0.due.map { Calendar.current.isDate($0,inSameDayAs: day) } == true && (mode != "课表" || $0.special == "course") }.sorted { ($0.due ?? .distantFuture) < ($1.due ?? .distantFuture) } }
    func dayEvents(_ day: Date) -> [ExternalEvent] { service.events.filter { Calendar.current.isDate($0.start,inSameDayAs: day) } }
    func monthGrid(_ value: Date,mini: Bool) -> some View {
        let c = Calendar.current; let first = c.date(from: c.dateComponents([.year,.month],from: value))!; let leading = (c.component(.weekday,from: first) - c.firstWeekday + 7) % 7
        let count = c.range(of: .day,in: .month,for: first)!.count; let total = ((leading + count + 6) / 7) * 7
        return VStack(spacing: 2) { HStack { ForEach(0..<7,id: \.self) { i in Text(["日","一","二","三","四","五","六"][(c.firstWeekday - 1 + i) % 7]).font(.caption).frame(maxWidth: .infinity) } }
            LazyVGrid(columns: Array(repeating: GridItem(.flexible(),spacing: 2),count: 7),spacing: 2) { ForEach(0..<total,id: \.self) { index in let day = c.date(byAdding: .day,value: index - leading,to: first)!; VStack(alignment: .leading,spacing: 5) { HStack { Text("\(c.component(.day,from: day))").font(mini ? .caption : .body).foregroundStyle(c.isDateInToday(day) ? Color.accentColor : c.component(.month,from: day) == c.component(.month,from: value) ? .primary : .secondary); Spacer(); if !mini { Button { create(on: day) } label: { Image(systemName: "plus").font(.caption2) }.buttonStyle(.plain) } }; if mini { if !dayTasks(day).isEmpty { Circle().fill(Color.accentColor).frame(width: 4,height: 4) } } else { dayContent(day,limit: compact ? 2 : 4) }; Spacer(minLength: 0) }.padding(mini ? 3 : 8).frame(minHeight: mini ? 28 : compact ? 85 : 110).background(c.isDateInToday(day) ? Color.accentColor.opacity(0.08) : Color.gray.opacity(0.04)).onTapGesture { if mini { date = day; mode = "日" } }.dropDestination(for: String.self) { values,_ in move(values,to: day); return true } } }
        }
    }
    func dayContent(_ day: Date,limit: Int) -> some View { VStack(alignment: .leading,spacing: 4) { ForEach(dayTasks(day).prefix(limit)) { t in Button { store.selectedTask = t.id; editing = t.id } label: { HStack(spacing: 4) { if t.completed { Image(systemName: "checkmark") }; Text(t.title).lineLimit(1) }.font(.caption).frame(maxWidth: .infinity,alignment: .leading).padding(4).background(color(t).opacity(0.13),in: RoundedRectangle(cornerRadius: 4)).foregroundStyle(color(t)) }.buttonStyle(.plain).draggable(t.id.uuidString) }
        ForEach(dayEvents(day).prefix(limit)) { e in Text(e.title).font(.caption).lineLimit(1).padding(3).background(Color.purple.opacity(0.1)).help("\(e.source) · \(e.start.formatted())") }
        if showHabits { ForEach(store.habits.filter { !$0.deleted && $0.weekdays.contains(Calendar.current.component(.weekday,from: day)) }.prefix(limit)) { h in Text("\(h.emoji) \(h.name) \(h.count(on: day))/\(h.goal)").font(.caption2).foregroundStyle(.green).lineLimit(1) } }
        if showFocus { let seconds = store.focus.filter { !$0.deleted && Calendar.current.isDate($0.started,inSameDayAs: day) }.reduce(0) { $0 + $1.seconds }; if seconds > 0 { Text("专注 \(Int(seconds / 60)) 分钟").font(.caption2).foregroundStyle(.orange) } }
    } }
    var timeGrid: some View { let c = Calendar.current; let count = mode == "日" ? 1 : 7; let base = count == 1 ? c.startOfDay(for: date) : c.dateInterval(of: .weekOfYear,for: date)!.start
        return ScrollView([.vertical,.horizontal]) { VStack(spacing: 0) { HStack { Text("时间").frame(width: 95); ForEach(0..<count,id: \.self) { offset in let day = c.date(byAdding: .day,value: offset,to: base)!; VStack { Text(day,format: .dateTime.weekday().day()).font(.headline); ForEach(dayTasks(day).filter(\.allDay)) { t in Text(t.title).font(.caption).lineLimit(1).onTapGesture { store.selectedTask = t.id; editing = t.id }.draggable(t.id.uuidString) } }.frame(width: mode == "日" ? 550 : 140) } }
            ForEach(0..<24,id: \.self) { hour in HStack(alignment: .top,spacing: 0) { VStack { Text(String(format: "%02d:00",hour)); let reference = c.date(bySettingHour: hour,minute: 0,second: 0,of: base)!; Text(zoneLabel(reference)).font(.caption2).foregroundStyle(.secondary) }.frame(width: 95); ForEach(0..<count,id: \.self) { offset in let day = c.date(byAdding: .day,value: offset,to: base)!; VStack(alignment: .leading,spacing: 2) { ForEach(dayTasks(day).filter { !$0.allDay && c.component(.hour,from: $0.start ?? $0.due!) == hour }) { t in Text(t.title).font(.caption).padding(5).frame(maxWidth: .infinity,alignment: .leading).background(color(t).opacity(0.18),in: RoundedRectangle(cornerRadius: 5)).onTapGesture { store.selectedTask = t.id; editing = t.id }.draggable(t.id.uuidString) }; ForEach(dayEvents(day).filter { c.component(.hour,from: $0.start) == hour }) { e in Text(e.title).font(.caption).foregroundStyle(.purple) }; Spacer(minLength: 0) }.frame(width: mode == "日" ? 550 : 140,height: zoom).background(Color.gray.opacity(0.025)).border(.quaternary,width: 0.5).dropDestination(for: String.self) { values,_ in move(values,to: c.date(bySettingHour: hour,minute: 0,second: 0,of: day)!); return true } } } }
        } }
    }
    func zoneLabel(_ value: Date) -> String { let f = DateFormatter(); f.timeZone = TimeZone(identifier: secondaryZone); f.dateFormat = "HH:mm"; return f.string(from: value) }
    func color(_ task: TaskItem) -> Color { store.lists.first { $0.id == task.listID }?.color.listColor ?? .blue }
    func move(_ values: [String],to day: Date) { for raw in values { if let id = UUID(uuidString: raw) { store.mutate(id) { Scheduling.move(&$0,to: day,timed: ["日","周","课表"].contains(mode)) } } } }
    func create(on day: Date) { if let id = store.add("新任务") { store.mutate(id) { $0.due = day }; editing = id } }
}
struct MatrixView: View {
    @EnvironmentObject var store: Store; @EnvironmentObject var calendar: CalendarService; @EnvironmentObject var focus: FocusTimer
    var body: some View { VStack(alignment: .leading,spacing: 20) { Text("四象限").font(.largeTitle.bold()); Text("按重要性和紧迫性安排任务，拖动任务可调整优先级与日期。 ").foregroundStyle(.secondary); Grid(horizontalSpacing: 16,verticalSpacing: 16) { GridRow { quadrant(0,"重要且紧急",.red); quadrant(1,"重要不紧急",.orange) }; GridRow { quadrant(2,"紧急不重要",.blue); quadrant(3,"不紧急不重要",.green) } } }.padding(24) }
    func index(_ t: TaskItem) -> Int { let important = t.priority >= 2; let urgent = t.due.map { $0 < Calendar.current.date(byAdding: .day,value: 1,to: Calendar.current.startOfDay(for: Date()))! } ?? false; return important ? (urgent ? 0 : 1) : (urgent ? 2 : 3) }
    func quadrant(_ i: Int,_ name: String,_ color: Color) -> some View { VStack(alignment: .leading) { Text(name).font(.headline).foregroundStyle(color); ScrollView { LazyVStack(alignment: .leading,spacing: 12) { ForEach(store.tasks.filter { !$0.deleted && !$0.completed && !$0.isTemplate && index($0) == i }) { t in HStack { Button { store.complete(t.id) } label: { Image(systemName: "circle") }.buttonStyle(.plain); Text(t.title); Spacer() }.padding(10).background(.background,in: RoundedRectangle(cornerRadius: 8)).draggable(t.id.uuidString).onTapGesture { store.selectedTask = t.id; DesktopBridge.panel(title: t.title,view: TaskDetailView().environmentObject(store).environmentObject(calendar).environmentObject(focus),floating: false) } } } } }.padding(18).frame(maxWidth: .infinity,minHeight: 220,maxHeight: .infinity).background(color.opacity(0.07),in: RoundedRectangle(cornerRadius: 16)).dropDestination(for: String.self) { values,_ in for raw in values { if let id = UUID(uuidString: raw) { store.mutate(id) { t in t.priority = i < 2 ? 3 : 0; t.due = i == 0 || i == 2 ? Date() : Calendar.current.date(byAdding: .day,value: 7,to: Date()) } } }; return true } }
}
