import SwiftUI
import AppKit
import ServiceManagement
import UniformTypeIdentifiers

struct SettingsView: View {
    @EnvironmentObject var store: Store; @EnvironmentObject var calendar: CalendarService; @EnvironmentObject var focus: FocusTimer
    @AppStorage("appearance") var appearance = "system"; @AppStorage("accent") var accent = "blue"; @AppStorage("fontScale") var fontScale = 14.0; @AppStorage("cloudEnabled") var cloudEnabled = false; @AppStorage("focusSound") var focusSound = true; @AppStorage("quickKey") var quickKey = 0
    @AppStorage("defaultDocumentMode") var defaultDocumentMode = DocumentEditingMode.richText.rawValue
    @State private var status = ""; @State private var login = false; @State private var subscriptionName = ""; @State private var subscriptionURL = ""; @State private var importPreview: ImportPreview?; @State private var showImport = false
    var body: some View { TabView {
        Form { Picker("默认正文编辑方式",selection: $defaultDocumentMode) { ForEach(DocumentEditingMode.allCases,id: \.self) { mode in Text(mode.title).tag(mode.rawValue) } }; Text("用于新任务；已有任务保留各自的编辑方式。").font(.caption).foregroundStyle(.secondary); Picker("外观",selection: $appearance) { Text("跟随系统").tag("system"); Text("浅色").tag("light"); Text("深色").tag("dark") }; ThemeColorChoices(title: "主题色",selection: $accent); Slider(value: $fontScale,in: 12...20,step: 1) { Text("字号 \(Int(fontScale))") }; Picker("全局快速添加",selection: $quickKey) { Text("⌘⌥A").tag(0); Text("⌘⌥Q").tag(1) }.onChange(of: quickKey) { _,value in UserDefaults.standard.removeObject(forKey: "quickCode"); UserDefaults.standard.removeObject(forKey: "quickModifiers"); UserDefaults.standard.removeObject(forKey: "quickShortcutLabel"); DesktopBridge.registerHotkey() }; ShortcutRecorder(); Toggle("专注结束声音",isOn: $focusSound); Toggle("登录时启动",isOn: $login).onChange(of: login) { _,value in do { if value { try SMAppService.mainApp.register() } else { try SMAppService.mainApp.unregister() } } catch { status = error.localizedDescription } }; Button("开启系统通知") { Task { do { status = try await NotificationService.shared.request() ? "通知已开启" : "请在系统设置中开启通知"; store.reschedule() } catch { status = error.localizedDescription } } }; Text(status).font(.caption).foregroundStyle(.secondary) }.padding().tabItem { Label("通用",systemImage: "gearshape") }
        Form { Toggle("启用 iCloud 同步",isOn: $cloudEnabled).disabled(!Capability.cloudAvailable); if !Capability.cloudAvailable { Text("此本地构建尚无 iCloud 授权；请使用 Xcode 配置开发者团队与 CloudKit 容器后构建。").font(.caption).foregroundStyle(.orange) }; Text("需要带 iCloud 授权的签名构建，并登录 Apple 账号。更改后重启应用生效；数据始终保留在本机。").font(.caption).foregroundStyle(.secondary); Text("状态：\(store.syncStatus)"); Button("重新读取同步数据") { store.reload() }; Divider(); HStack { Button("导出备份") { export() }; Button("导入 / 恢复") { importFile() } }; Button("立即备份") { do { try store.manualBackup(); status = "已保存长期备份" } catch { status = error.localizedDescription } }; Button("打开备份文件夹") { NSWorkspace.shared.open(store.persistence.root) }; Text("自动备份保留最近 30 天；手动备份长期保留。").font(.caption); Text(status).font(.caption).foregroundStyle(.secondary) }.padding().tabItem { Label("数据",systemImage: "externaldrive") }
        Form { Button("连接系统日历") { Task { await calendar.authorize() } }; Button("导入 Apple 提醒事项") { Task { await calendar.importReminders(into: store) } }; Text(calendar.message).font(.caption); Divider(); Text("ICS 日历订阅").font(.headline); TextField("名称",text: $subscriptionName); TextField("https://…/calendar.ics",text: $subscriptionURL); Button("添加订阅") { Task { do { try await calendar.subscribe(subscriptionURL,name: subscriptionName); store.save(CalendarSubscription(name: subscriptionName,url: subscriptionURL)); subscriptionName = ""; subscriptionURL = "" } catch { calendar.message = error.localizedDescription } } }.disabled(subscriptionName.isEmpty || subscriptionURL.isEmpty); ForEach(store.subscriptions.filter { !$0.deleted }) { sub in HStack { Text(sub.name); Spacer(); Button("刷新") { Task { do { try await calendar.subscribe(sub.url,name: sub.name) } catch { calendar.message = error.localizedDescription } } }; Button("移除") { var s = sub; s.deleted = true; store.save(s); calendar.events.removeAll { $0.source == sub.name } } } }; Text("支持日期、时区及常用重复规则；不支持的规则会显示错误，请勿将订阅错误视为完整导入。").font(.caption).foregroundStyle(.secondary) }.padding().tabItem { Label("集成",systemImage: "calendar.badge.plus") }
        VStack(spacing: 16) { BrandIcon(size: 80); Text("Zilo").font(.title.bold()); Text("1.0 · 个人 Mac 工具"); Text("数据目录：\(store.persistence.root.path)").font(.caption).textSelection(.enabled); Text("快捷添加：⌘⌥A / ⌘⌥Q\n应用内：⌘N 添加 · ⌘Z 撤销 · ⇧⌘Z 重做\nURL：ownlist://add?title=任务内容").font(.caption) }.padding().tabItem { Label("关于",systemImage: "info.circle") }
    }.frame(width: 600,height: 520).tint(accent.listColor).accentColor(accent.listColor).preferredColorScheme(appearance == "dark" ? .dark : appearance == "light" ? .light : nil).onAppear { login = SMAppService.mainApp.status == .enabled }.sheet(isPresented: $showImport) { if let preview = importPreview { ImportView(preview: preview).environmentObject(store) } } }
    func export() { let p = NSSavePanel(); p.nameFieldStringValue = "Zilo-\(Day.key(Date())).ownlist.json"; p.allowedContentTypes = [.json]; if p.runModal() == .OK, let url = p.url { do { try store.export(to: url); status = "备份已导出" } catch { status = error.localizedDescription } } }
    func importFile() { let p = NSOpenPanel(); p.allowedContentTypes = [.json,.commaSeparatedText,.plainText]; if p.runModal() == .OK, let url = p.url { do { importPreview = try ImportService.preview(url); showImport = true } catch { status = error.localizedDescription } } }
}
