import SwiftUI
import AppKit
import Carbon

struct ShortcutRecorder: View {
    @State private var recording = false; @State private var monitor: Any?; @State private var label = UserDefaults.standard.string(forKey: "quickShortcutLabel") ?? "⌘⌥A"; @State private var error = ""
    var body: some View { VStack(alignment: .leading,spacing: 6) { HStack { Text("当前快捷键：\(label)"); Spacer(); Button(recording ? "按下组合键，Esc 取消" : "录制快捷键") { if recording { stop() } else { start() } }; Button("恢复默认") { UserDefaults.standard.removeObject(forKey: "quickCode"); UserDefaults.standard.removeObject(forKey: "quickModifiers"); UserDefaults.standard.removeObject(forKey: "quickShortcutLabel"); UserDefaults.standard.set(0,forKey: "quickKey"); label = "⌘⌥A"; DesktopBridge.registerHotkey() } }; if !error.isEmpty { Text(error).font(.caption).foregroundStyle(.orange) } }.onDisappear { stop() } }
    func start() { recording = true; error = ""; monitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { event in if event.keyCode == UInt16(kVK_Escape) { stop(); return nil }; let flags = event.modifierFlags.intersection(.deviceIndependentFlagsMask); guard flags.contains(.command) || flags.contains(.option) || flags.contains(.control) else { error = "请包含 Command、Option 或 Control 修饰键"; return nil }; var modifiers: UInt32 = 0; var prefix = ""; if flags.contains(.control) { modifiers |= UInt32(controlKey); prefix += "⌃" }; if flags.contains(.option) { modifiers |= UInt32(optionKey); prefix += "⌥" }; if flags.contains(.shift) { modifiers |= UInt32(shiftKey); prefix += "⇧" }; if flags.contains(.command) { modifiers |= UInt32(cmdKey); prefix += "⌘" }; label = prefix + (event.charactersIgnoringModifiers?.uppercased() ?? "按键 \(event.keyCode)"); UserDefaults.standard.set(Int(event.keyCode),forKey: "quickCode"); UserDefaults.standard.set(Int(modifiers),forKey: "quickModifiers"); UserDefaults.standard.set(label,forKey: "quickShortcutLabel"); DesktopBridge.registerHotkey(); if DesktopBridge.hotKeyError != noErr { error = "此快捷键无法注册，可能已被其他应用占用，请选择另一组合。" }; stop(); return nil } }
    func stop() { if let monitor { NSEvent.removeMonitor(monitor) }; monitor = nil; recording = false }
}
