import SwiftUI
import Charts

struct FocusView: View {
    @EnvironmentObject var store: Store; @EnvironmentObject var timer: FocusTimer
    @State private var addMinutes = 5.0
    var body: some View { ScrollView { VStack(spacing: 24) { HStack { Text("专注").font(.largeTitle.bold()); Spacer(); Button("小窗口") { DesktopBridge.panel(title: "专注",view: FocusMiniView().environmentObject(timer),size: NSSize(width: 260,height: 180)) } }
        Picker("模式",selection: $timer.mode) { Text("番茄钟").tag("番茄"); Text("正计时").tag("正计时") }.pickerStyle(.segmented).frame(width: 300).disabled(timer.running)
        ZStack { Circle().stroke(.quaternary,lineWidth: 12); Circle().trim(from: 0,to: timer.mode == "番茄" ? min(1,timer.elapsed / Double(max(1,timer.minutes) * 60)) : 1).stroke(Color.accentColor,style: StrokeStyle(lineWidth: 12,lineCap: .round)).rotationEffect(.degrees(-90)); VStack { Text(timer.phase).foregroundStyle(.secondary); Text(timer.display).font(.system(size: 64,weight: .light,design: .rounded)).monospacedDigit() } }.frame(width: 300,height: 300)
        Picker("关联任务",selection: $timer.taskID) { Text("自由专注").tag(nil as UUID?); ForEach(store.tasks.filter { !$0.deleted && !$0.completed && !$0.isTemplate }) { Text($0.title).tag(Optional($0.id)) } }.frame(maxWidth: 450)
        HStack { Button(timer.running ? "暂停" : "开始") { if timer.running { timer.pause() } else { timer.start() } }.buttonStyle(.borderedProminent).controlSize(.large); Button("结束并记录") { timer.stop() }.controlSize(.large) }
        HStack { Stepper("专注 \(timer.minutes) 分钟",value: $timer.minutes,in: 1...180); Stepper("短休息 \(timer.breakMinutes) 分钟",value: $timer.breakMinutes,in: 1...60); Stepper("长休息 \(timer.longBreakMinutes) 分钟",value: $timer.longBreakMinutes,in: 1...90) }.disabled(timer.running).onChange(of: timer.minutes) { _,value in UserDefaults.standard.set(value,forKey: "focusMinutes"); if !timer.running { timer.remaining = Double(value * 60) } }
        HStack { Text("补记专注"); Stepper("\(Int(addMinutes)) 分钟",value: $addMinutes,in: 1...720); Button("添加记录") { store.save(FocusRecord(taskID: timer.taskID,started: Date().addingTimeInterval(-addMinutes * 60),seconds: addMinutes * 60,mode: "补记")) } }.padding().background(ListTheme.input,in: RoundedRectangle(cornerRadius: 12))
        VStack(alignment: .leading,spacing: 12) { Text("最近记录").font(.title2.bold()); ForEach(store.focus.filter { !$0.deleted }.sorted { $0.started > $1.started }.prefix(30)) { r in HStack { Text(r.started,format: .dateTime.month().day().hour().minute()); Text(store.tasks.first { $0.id == r.taskID }?.title ?? "自由专注"); Spacer(); Text("\(Int(r.seconds / 60)) 分钟 · \(r.mode)"); Button { var record = r; record.deleted = true; store.save(record) } label: { Image(systemName: "trash") }.buttonStyle(.plain) } } }
    }.padding(30).frame(maxWidth: 950) }.frame(maxWidth: .infinity) }
}
struct FocusMiniView: View { @EnvironmentObject var timer: FocusTimer; var body: some View { VStack(spacing: 12) { Text(timer.phase).foregroundStyle(.secondary); Text(timer.display).font(.system(size: 40,design: .rounded)).monospacedDigit(); HStack { Button(timer.running ? "暂停" : "开始") { if timer.running { timer.pause() } else { timer.start() } }; Button("结束") { timer.stop() } } }.padding().frame(maxWidth: .infinity,maxHeight: .infinity) } }
struct HabitsView: View {
    @EnvironmentObject var store: Store; @State private var date = Date(); @State private var editor = false; @State private var existing: Habit?
    var body: some View { VStack(alignment: .leading,spacing: 20) { HStack { Text("习惯").font(.largeTitle.bold()); Spacer(); DatePicker("打卡日期",selection: $date,in: ...Date(),displayedComponents: .date); Button("新建习惯") { existing = nil; editor = true }.buttonStyle(.borderedProminent) }; ScrollView { LazyVGrid(columns: [GridItem(.adaptive(minimum: 280))],spacing: 18) { ForEach(store.habits.filter { !$0.deleted }) { habit in VStack(alignment: .leading,spacing: 15) { HStack { Text(habit.emoji).font(.largeTitle); Text(habit.name).font(.title3.bold()); Spacer(); Menu { Button("编辑") { existing = habit; editor = true }; Button("删除",role: .destructive) { var h = habit; h.deleted = true; store.save(h) } } label: { Image(systemName: "ellipsis") } }; HStack { Text("\(habit.count(on: date)) / \(habit.goal)").font(.title2.monospacedDigit()); Spacer(); Button { update(habit,-1) } label: { Image(systemName: "minus") }.disabled(habit.count(on: date) == 0); Button(habit.count(on: date) >= habit.goal ? "已达标 · 再记一次" : "打卡") { update(habit,1) }.buttonStyle(.borderedProminent) }; Text("连续 \(habit.streak()) 次 · 累计 \(habit.logs.values.reduce(0,+)) 次").foregroundStyle(.secondary); HStack(spacing: 4) { ForEach(0..<28,id: \.self) { i in let day = Calendar.current.date(byAdding: .day,value: i - 27,to: Calendar.current.startOfDay(for: date))!; RoundedRectangle(cornerRadius: 3).fill(habit.count(on: day) >= habit.goal ? Color.green : habit.count(on: day) > 0 ? Color.green.opacity(0.35) : Color.gray.opacity(0.12)).frame(height: 20).help("\(Day.key(day)): \(habit.count(on: day))").onTapGesture { date = day } } }; Text("最近 28 天 · 点击格子补记").font(.caption).foregroundStyle(.secondary) }.padding(20).background(ListTheme.input,in: RoundedRectangle(cornerRadius: 16)) } } }.frame(maxHeight: store.habits.contains(where: { !$0.deleted }) ? .infinity : 0)
        if store.habits.filter({ !$0.deleted }).isEmpty { ContentUnavailableView("养成一个小习惯",systemImage: "leaf",description: Text("设置每天的目标，记录一点一滴的进步。")) .frame(maxWidth: .infinity,maxHeight: .infinity) }
    }.padding(24).sheet(isPresented: $editor) { HabitEditor(existing: existing).environmentObject(store) } }
    func update(_ habit: Habit,_ amount: Int) { var h = habit; h.logs[Day.key(date)] = max(0,h.count(on: date) + amount); store.save(h) }
}
struct HabitEditor: View {
    @EnvironmentObject var store: Store; @Environment(\.dismiss) var dismiss; var existing: Habit?; @State private var habit = Habit(name: "")
    var body: some View { VStack(alignment: .leading,spacing: 18) { Text("习惯设置").font(.title2.bold()); Form { TextField("名称",text: $habit.name); TextField("图标",text: $habit.emoji); Stepper("每次目标 \(habit.goal)",value: $habit.goal,in: 1...1000); WeekdayPicker(days: $habit.weekdays); Picker("提醒时间",selection: $habit.reminderHour) { Text("不提醒").tag(-1); ForEach(0..<24,id: \.self) { Text("\($0):00").tag($0) } } }; HStack { Button("取消") { dismiss() }; Spacer(); Button("保存") { store.save(habit); dismiss() }.buttonStyle(.borderedProminent).disabled(habit.name.isEmpty || habit.weekdays.isEmpty) } }.padding(24).frame(width: 450).onAppear { if let existing { habit = existing } } }
}
struct StatisticsView: View {
    @EnvironmentObject var store: Store; @State private var days = 30
    var body: some View { ScrollView { VStack(alignment: .leading,spacing: 25) { HStack { Text("统计与回顾").font(.largeTitle.bold()); Spacer(); Picker("范围",selection: $days) { Text("7 天").tag(7); Text("30 天").tag(30); Text("90 天").tag(90) }.frame(width: 120) }
        HStack(spacing: 20) { card("完成任务","\(completed.count)","checkmark.circle",.blue); card("专注分钟","\(Int(records.reduce(0) { $0 + $1.seconds } / 60))","timer",.orange); card("习惯达标","\(habitDays)","leaf",.green) }
        Text("每日完成任务").font(.title2.bold()); Chart { ForEach(0..<days,id: \.self) { i in let d = Calendar.current.date(byAdding: .day,value: i - days + 1,to: Calendar.current.startOfDay(for: Date()))!; BarMark(x: .value("日期",d,unit: .day),y: .value("完成",completed.filter { $0.completedAt.map { Calendar.current.isDate($0,inSameDayAs: d) } == true }.count)).foregroundStyle(.blue) } }.frame(height: 230)
        Text("每日专注时长").font(.title2.bold()); Chart { ForEach(0..<days,id: \.self) { i in let d = Calendar.current.date(byAdding: .day,value: i - days + 1,to: Calendar.current.startOfDay(for: Date()))!; LineMark(x: .value("日期",d,unit: .day),y: .value("分钟",records.filter { Calendar.current.isDate($0.started,inSameDayAs: d) }.reduce(0) { $0 + $1.seconds / 60 })).foregroundStyle(.orange) } }.frame(height: 230)
        Text("清单完成分布").font(.title2.bold()); ForEach(store.lists.filter { !$0.deleted }) { l in HStack { Circle().fill(l.color.listColor).frame(width: 10,height: 10); Text(l.name); Spacer(); Text("\(completed.filter { $0.listID == l.id }.count) 项") } }
    }.padding(30) } }
    var cutoff: Date { Calendar.current.date(byAdding: .day,value: 1 - days,to: Calendar.current.startOfDay(for: Date()))! }
    var completed: [TaskItem] { store.tasks.filter { !$0.deleted && $0.completed && $0.completedAt.map { $0 >= cutoff } == true } }
    var records: [FocusRecord] { store.focus.filter { !$0.deleted && $0.started >= cutoff } }
    var habitDays: Int { store.habits.filter { !$0.deleted }.reduce(0) { count,h in count + h.logs.filter { (Day.date($0.key) ?? .distantPast) >= cutoff && $0.value >= h.goal }.count } }
    func card(_ title: String,_ value: String,_ icon: String,_ color: Color) -> some View { VStack(alignment: .leading,spacing: 12) { Label(title,systemImage: icon).foregroundStyle(color); Text(value).font(.system(size: 36,weight: .semibold,design: .rounded)) }.padding(24).frame(maxWidth: .infinity,alignment: .leading).background(color.opacity(0.08),in: RoundedRectangle(cornerRadius: 16)) }
}
